deps_config := \
	test/yunit/Config.in \
	test/testcase/certificate/certificate_test/Config.in \
	test/testcase/certificate/Config.in \
	test/testcase/3rdparty/experimental/fs/fatfs/Config.in \
	test/testcase/3rdparty/experimental/fs/spiffs/Config.in \
	test/testcase/3rdparty/experimental/Config.in \
	test/testcase/osal/cmsis/Config.in \
	test/testcase/osal/posix/Config.in \
	test/testcase/osal/aos/Config.in \
	test/testcase/osal/Config.in \
	test/testcase/utility/cjson/Config.in \
	test/testcase/utility/Config.in \
	test/testcase/kernel/basic/Config.in \
	test/testcase/kernel/fs/vfs/Config.in \
	test/testcase/kernel/fs/ramfs/Config.in \
	test/testcase/kernel/fs/kv/Config.in \
	test/testcase/kernel/rhino/Config.in \
	test/testcase/kernel/Config.in \
	test/testcase/Config.in \
	test/Config.in \
	utility/zlib/Config.in \
	utility/mbedtls/Config.in \
	utility/libc/Config.in \
	utility/cjson/Config.in \
	utility/activation/chip_code/Config.in \
	utility/activation/Config.in \
	utility/Config.in \
	security/prov/Config.in \
	security/mbedtls/Config.in \
	security/itls/Config.in \
	security/isst/Config.in \
	security/irot/tee/Config.in \
	security/irot/se/Config.in \
	security/irot/km/Config.in \
	security/irot/Config.in \
	security/id2/Config.in \
	security/dpm/Config.in \
	security/alicrypto/Config.in \
	security/ls_hal/Config.in \
	security/ls_osa/Config.in \
	security/Config.in \
	middleware/ulocation/Config.in \
	middleware/udata/Config.in \
	middleware/uagent/ota/2nd_boot/Config.in \
	middleware/uagent/ota/ota_ble/Config.in \
	middleware/uagent/ota/Config.in \
	middleware/uagent/ulog/Config.in \
	middleware/uagent/udev/Config.in \
	middleware/uagent/Config.in \
	middleware/linkkit/sdk-c/src/ref-impl/hal/os/alios/Config.in \
	middleware/linkkit/sdk-c/src/protocol/http2/Config.in \
	middleware/linkkit/sdk-c/src/services/http2_stream/Config.in \
	middleware/linkkit/sdk-c/src/services/awss/Config.in \
	middleware/linkkit/sdk-c/src/services/mdal/sal/Config.in \
	middleware/linkkit/sdk-c/src/services/mdal/mal/Config.in \
	middleware/linkkit/sdk-c/src/services/mdal/Config.in \
	middleware/linkkit/sdk-c/src/sdk-impl/Config.in \
	middleware/linkkit/sdk-c/src/protocol/http/Config.in \
	middleware/linkkit/sdk-c/src/protocol/coap/client/Config.in \
	middleware/linkkit/sdk-c/src/services/linkkit/dev_reset/Config.in \
	middleware/linkkit/sdk-c/src/services/dev_bind/Config.in \
	middleware/linkkit/sdk-c/src/protocol/coap/server/Config.in \
	middleware/linkkit/sdk-c/src/sdk-impl/Config.in \
	middleware/linkkit/sdk-c/src/infra/utils/Config.in \
	middleware/linkkit/sdk-c/src/infra/system/Config.in \
	middleware/linkkit/sdk-c/src/infra/log/Config.in \
	middleware/linkkit/sdk-c/src/protocol/alcs/Config.in \
	middleware/linkkit/sdk-c/src/infra/utils/Config.in \
	middleware/linkkit/sdk-c/src/infra/utils/Config.in \
	middleware/linkkit/sdk-c/src/infra/system/Config.in \
	middleware/linkkit/sdk-c/src/infra/log/Config.in \
	middleware/linkkit/sdk-c/src/services/linkkit/dm/Config.in \
	middleware/linkkit/sdk-c/src/infra/utils/Config.in \
	middleware/linkkit/sdk-c/src/infra/log/Config.in \
	middleware/linkkit/sdk-c/src/services/linkkit/cm/Config.in \
	middleware/linkkit/sdk-c/src/services/linkkit/Config.in \
	middleware/linkkit/sdk-c/src/infra/utils/Config.in \
	middleware/linkkit/sdk-c/src/infra/system/Config.in \
	middleware/linkkit/sdk-c/src/infra/log/Config.in \
	middleware/linkkit/sdk-c/src/protocol/mqtt/Config.in \
	middleware/linkkit/sdk-c/Config.linkkit \
	middleware/linkkit/Config.in \
	network/yloop/Config.in \
	network/umesh/Config.in \
	network/netmgr/Config.in \
	network/lwip/Config.in \
	network/lorawan/lorawan_4_4_2/Config.in \
	network/lorawan/lorawan_4_4_0/Config.in \
	network/lorawan/Config.in \
	network/canopen/Config.in \
	network/bluetooth/tmall_model/Config.in \
	network/bluetooth/bt_mesh/Config.in \
	network/bluetooth/bt_host/profile/Config.in \
	network/bluetooth/bt_host/bt_common/Config.in \
	network/bluetooth/bt_host/Config.in \
	network/bluetooth/breeze/ref-impl/Config.in \
	network/bluetooth/breeze/Config.in \
	network/Config.in \
	drivers/sensor/Config.in \
	drivers/Config.in \
	osal/cmsis/Config.in \
	osal/posix/Config.in \
	osal/aos/Config.in \
	kernel/bus/usb/Config.in \
	kernel/bus/mbmaster/Config.in \
	kernel/fs/vfs/Config.in \
	kernel/fs/ramfs/Config.in \
	kernel/fs/kv/Config.in \
	kernel/cplusplus/Config.in \
	kernel/mbins/Config.in \
	kernel/pwrmgmt/Config.in \
	kernel/debug/Config.in \
	kernel/cli/Config.in \
	kernel/init/Config.in \
	kernel/rhino/Config.in \
	kernel/Config.in \
	board/xr871evb/Config.in \
	platform/mcu/xr871/Config.in \
	board/xr809/Config.in \
	platform/mcu/xm510/Config.in \
	board/xm510_evb/Config.in \
	platform/mcu/wm_w600/Config.in \
	board/wm_w600_kit/Config.in \
	platform/mcu/rda5981x/Config.in \
	board/uno-91h/Config.in \
	platform/mcu/sv6266/Config.in \
	board/sv6266_evb/Config.in \
	board/stm32l496g-discovery/Config.in \
	board/stm32l476rg-nucleo/Config.in \
	board/stm32l433rc-nucleo/Config.in \
	board/stm32l432kc-nucleo/Config.in \
	platform/mcu/stm32f7xx/Config.in \
	board/stm32f769i-discovery/Config.in \
	board/stm32f429zi-nucleo/Config.in \
	board/stm32f412zg-nucleo/Config.in \
	board/stm32f411re-nucleo/Config.in \
	platform/mcu/stm32f4xx_cube/Config.in \
	board/stm32f401re-nucleo/Config.in \
	platform/mcu/stm32f1xx/Config.in \
	board/stm32f103rb-nucleo/Config.in \
	platform/mcu/stm32f0xx/Config.in \
	board/stm32f091rc-nucleo/Config.in \
	board/starterkit/Config.in \
	platform/mcu/sscp131/Config.in \
	board/ssc1667/Config.in \
	platform/mcu/atsaml21/Config.in \
	board/saml21_iot_sk/Config.in \
	board/rk1108/Config.in \
	platform/arch/mips/mips-I/Config.in \
	platform/mcu/rda8955/Config.in \
	board/rda8955/Config.in \
	board/pca10056/Config.in \
	board/pca10040e/Config.in \
	platform/mcu/nrf52xxx/Config.in \
	board/pca10040/Config.in \
	board/nutiny-evb-nano130/Config.in \
	platform/mcu/nano130ke3bn/Config.in \
	board/numaker-pfm-nano130/Config.in \
	platform/mcu/m487jidae/Config.in \
	board/numaker-pfm-m487/Config.in \
	platform/mcu/msp432p4xx/Config.in \
	board/msp432p4111launchpad/Config.in \
	board/mk3239/Config.in \
	board/mk3166/Config.in \
	platform/mcu/stm32f4xx/Config.in \
	board/mk3165/Config.in \
	board/mk3080/Config.in \
	platform/mcu/moc108/Config.in \
	board/mk3060/Config.in \
	platform/mcu/mx1101/Config.in \
	board/mk1101/Config.in \
	board/m400/Config.in \
	platform/mcu/efm32gxx/Config.in \
	board/m100c/Config.in \
	platform/mcu/lpc54628/Config.in \
	board/lpcxpresso54628/Config.in \
	platform/mcu/lpc54608/Config.in \
	board/lpcxpresso54608/Config.in \
	platform/mcu/lpc54114/Config.in \
	board/lpcxpresso54114/Config.in \
	platform/mcu/lpc54102/Config.in \
	board/lpcxpresso54102/Config.in \
	platform/mcu/lpc54018/Config.in \
	board/lpcxpresso54018/Config.in \
	platform/arch/linux/Config.in \
	platform/mcu/linux/Config.in \
	board/linuxhost/Config.in \
	board/imx6sl/Config.in \
	platform/arch/arm/armv7a/Config.in \
	platform/mcu/imx6/Config.in \
	board/imx6dq/Config.in \
	board/hr8p296fllt/Config.in \
	platform/mcu/hr8p2xx/Config.in \
	board/hr8p287fjlt/Config.in \
	platform/mcu/hk32f103/Config.in \
	board/hk32f103rb_evb/Config.in \
	platform/arch/risc-v/risc_v32I/Config.in \
	platform/mcu/freedom-e/e310/Config.in \
	board/hifive1/Config.in \
	platform/mcu/hc32l136/Config.in \
	board/hc32l136k8ta/Config.in \
	platform/mcu/gd32f4xx/Config.in \
	board/gd32f450z-eval/Config.in \
	platform/mcu/gd32f3x0/Config.in \
	board/gd32f350r-eval/Config.in \
	platform/mcu/gd32f30x/Config.in \
	board/gd32f307c-eval/Config.in \
	platform/mcu/mkl82z7/Config.in \
	board/frdmkl82z/Config.in \
	platform/mcu/mkl81z7/Config.in \
	board/frdmkl81z/Config.in \
	platform/mcu/mkl43z4/Config.in \
	board/frdmkl43z/Config.in \
	platform/mcu/mkl28z7/Config.in \
	board/frdmkl28z/Config.in \
	platform/mcu/mkl27z644/Config.in \
	board/frdmkl27z/Config.in \
	platform/mcu/mkl26z4/Config.in \
	board/frdmkl26z/Config.in \
	platform/mcu/fm33a0xx/Config.in \
	board/fm33a0xx-discovery/Config.in \
	platform/mcu/mimxrt1021/Config.in \
	board/evkmimxrt1020/Config.in \
	platform/mcu/mimxrt1052/Config.in \
	board/evkbimxrt1050/Config.in \
	platform/arch/xtensa/lx106/Config.in \
	platform/mcu/esp8266/Config.in \
	board/esp8266/Config.in \
	board/esp32sram/Config.in \
	platform/arch/xtensa/lx6/Config.in \
	platform/mcu/esp32/Config.in \
	board/esp32devkitc/Config.in \
	platform/mcu/es8p508x/Config.in \
	board/es8p5088fllq/Config.in \
	platform/arch/arm/armv6m/Config.in \
	platform/mcu/stm32l0xx/Config.in \
	board/eml3047/Config.in \
	platform/mcu/dahua/Config.in \
	board/dh5021a_evb/Config.in \
	platform/mcu/stm32l4xx_cube/Config.in \
	board/developerkit/Config.in \
	platform/mcu/cy8c6347/Config.in \
	board/cy8ckit-062/Config.in \
	platform/arch/csky/cskyv2-l/Config.in \
	platform/mcu/csky/Config.in \
	board/cb2201/Config.in \
	platform/mcu/bk7231u/Config.in \
	board/bk7231udevkitc/Config.in \
	platform/arch/arm/armv5/Config.in \
	platform/mcu/bk7231/Config.in \
	board/bk7231devkitc/Config.in \
	platform/mcu/stm32l475/Config.in \
	board/b_l475e/Config.in \
	platform/mcu/atsamd5x_e5x/Config.in \
	board/atsame54-xpro/Config.in \
	platform/mcu/mvs_ap80xx/Config.in \
	board/ap80a0/Config.in \
	platform/mcu/rtl8710bn/Config.in \
	board/amebaz_dev/Config.in \
	platform/arch/arm/armv7m/Config.in \
	platform/mcu/aamcu_demo/Config.in \
	board/aaboard_demo/Config.in \
	board/Config.in \
	app/Config.in \
	app/profile/gatewayapp/Config.in \
	app/profile/Config.in \
	app/example/yts/Config.in \
	app/example/ulocationapp/Config.in \
	app/example/udevapp/Config.in \
	app/example/udataapp/Config.in \
	app/example/uart/Config.in \
	app/example/tls/Config.in \
	app/example/sk/sk_gui/Config.in \
	app/example/prov_app/Config.in \
	app/example/otaapp/Config.in \
	app/example/mqttapp/Config.in \
	app/example/modbus_demo/Config.in \
	app/example/meshapp/Config.in \
	app/example/lorawan/linkwan/Config.in \
	app/example/flydimming/Config.in \
	app/example/flyswitch/Config.in \
	app/example/flycurtain/Config.in \
	app/example/flylight/Config.in \
	app/example/linkkitapp/Config.in \
	app/example/linkkit_gateway/Config.in \
	app/example/itls_app/Config.in \
	app/example/id2_app/Config.in \
	app/example/http2app/Config.in \
	app/example/helloworld/Config.in \
	app/example/dk/dk_qr/Config.in \
	app/example/dk/dk_gui/Config.in \
	app/example/dk/dk_camera/Config.in \
	app/example/dk/dk_audio/Config.in \
	app/example/das_app/Config.in \
	app/example/coapapp/Config.in \
	app/example/bluetooth/breezeapp/Config.in \
	app/example/bluetooth/bleperipheral/Config.in \
	app/example/bluetooth/blemesh_tmall/Config.in \
	app/example/bluetooth/bleadv/Config.in \
	app/example/blink/Config.in \
	network/nal/athost/Config.in \
	app/example/athostapp/Config.in \
	app/example/Config.in \
	./build/Config.in

out/config/auto.conf: \
	$(deps_config)


$(deps_config): ;
